# Generated by Django 3.0.3 on 2020-05-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vau_form', '0002_auto_20200521_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='logo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
