# Generated by Django 3.0.3 on 2020-05-22 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vau_form', '0003_social_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('logo', models.CharField(max_length=100)),
                ('position', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vau_form.UserCard')),
            ],
        ),
    ]
