# Generated by Django 3.0.3 on 2020-05-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vau_form', '0004_artistnetwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
