# Generated by Django 3.0.3 on 2020-05-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vau_form', '0005_auto_20200522_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistnetwork',
            name='position',
        ),
        migrations.AddField(
            model_name='artistnetwork',
            name='name',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
