# Generated by Django 2.1.5 on 2020-10-26 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuthCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('user', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DocsRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=500)),
                ('release_name', models.CharField(max_length=500)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('release_date', models.DateField(default=None)),
                ('filthy', models.CharField(max_length=170)),
                ('number', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='Music/static/images/covers')),
                ('release_type', models.CharField(max_length=150)),
                ('vk_style', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Music/static/images/scans')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.DocsRequest')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('melody_author', models.CharField(max_length=250)),
                ('text_author', models.CharField(max_length=250)),
                ('singer', models.CharField(max_length=250)),
                ('artist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.Artist')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.DocsRequest')),
            ],
        ),
    ]
