# Generated by Django 2.1.5 on 2020-10-26 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='track',
            name='artist_name',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
