# Generated by Django 2.1.5 on 2020-10-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0005_auto_20201026_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artist_name',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
