# Generated by Django 2.1.5 on 2020-10-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0006_auto_20201026_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='photo',
            field=models.ImageField(upload_to='static/images/scans'),
        ),
    ]
