# Generated by Django 2.1.5 on 2020-10-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0007_auto_20201027_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsrequest',
            name='cover',
            field=models.ImageField(upload_to='MusicSite/Music/static/images/covers'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='photo',
            field=models.ImageField(upload_to='MusicSite/Music/static/images/scans'),
        ),
    ]
