# Generated by Django 2.1.5 on 2020-10-27 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0012_scan_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='photo_url',
        ),
    ]
