# Generated by Django 2.1.5 on 2020-10-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0013_remove_scan_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='photo_url',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
