# Generated by Django 2.1.5 on 2020-10-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0014_scan_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='full_name',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
