# Generated by Django 2.1.5 on 2020-11-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0015_track_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileToUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=250)),
                ('file', models.FileField(upload_to='Music/static/documents/offers')),
            ],
        ),
    ]
