# Generated by Django 2.1.5 on 2020-11-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0016_filetoupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetoupload',
            name='file',
            field=models.FileField(upload_to='Music/static/documents'),
        ),
    ]
