# Generated by Django 3.1.6 on 2021-02-14 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0017_auto_20201102_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaspInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default=None, max_length=500)),
                ('who_given', models.CharField(default=None, max_length=500)),
                ('when_given', models.CharField(default=None, max_length=500)),
                ('data_born', models.CharField(default=None, max_length=500)),
                ('place_born', models.CharField(default=None, max_length=500)),
                ('email', models.CharField(default=None, max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='FileToUpload',
        ),
        migrations.AddField(
            model_name='track',
            name='release_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='track',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Music.docsrequest'),
        ),
    ]
