# Generated by Django 3.1.6 on 2021-02-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0018_auto_20210214_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=500)),
                ('value', models.FloatField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='scan',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='request',
        ),
        migrations.AddField(
            model_name='docsrequest',
            name='artisi_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='paspinfo',
            name='artist_name',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='paspinfo',
            name='grajdanstvo',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='paspinfo',
            name='seria_num',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
